import L from "leaflet";
import { useEffect, useRef } from "react";
import type { CorridorMetric, Trajectory } from "../types/telemetry";

const cameras = [["Shankar Chowk", "GMDA-ANPR-SEC29-01", 28.5003, 77.0870], ["IFFCO Chowk", "GMDA-CAM-IFFCO-01", 28.4735, 77.0725], ["MG Road Metro", "GMDA-CAM-MGR-02", 28.4797, 77.0802], ["Sikanderpur", "GMDA-CAM-SIK-03", 28.4810, 77.0921], ["Genpact", "GMDA-CAM-GEN-01", 28.4932, 77.0925], ["Sector 54", "GMDA-CAM-GCR-04", 28.4430, 77.0865], ["Cyber City", "DLF-PHASE3-ENTRY-02", 28.4941, 77.0885], ["DLF Phase 3", "GMDA-CAM-CC-02", 28.4958, 77.0912]] as const;
const links = [[0, 1, "MG Road"], [3, 5, "Golf Course Road"], [4, 6, "Cyber City Underpass"]] as const;
const color = (metric?: CorridorMetric) => metric?.level === "CRITICAL_CONGESTION" ? "#dc2626" : metric?.level === "ADAPTIVE_SIGNAL" ? "#d97706" : "#16a34a";

export function MapView({ corridors, trajectory }: { corridors: CorridorMetric[]; trajectory?: Trajectory }) {
  const container = useRef<HTMLDivElement>(null); const map = useRef<L.Map | null>(null); const layer = useRef<L.LayerGroup | null>(null);
  useEffect(() => { if (!container.current || map.current) return; const current = L.map(container.current, { zoomControl: false }).setView([28.481, 77.092], 13); map.current = current; L.control.zoom({ position: "bottomright" }).addTo(current); L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png", { attribution: "© OpenStreetMap © CARTO", maxZoom: 20 }).addTo(current); return () => { current.remove(); map.current = null; }; }, []);
  useEffect(() => { const current = map.current; if (!current) return; layer.current?.remove(); const group = L.layerGroup().addTo(current); layer.current = group; links.forEach(([from, to, name]) => { const metric = corridors.find(item => item.corridor_id === name); const a = cameras[from], b = cameras[to]; L.polyline([[a[2], a[3]], [b[2], b[3]]], { color: color(metric), weight: 5, opacity: .76 }).bindTooltip(`${name}: ${metric?.space_mean_speed_kph.toFixed(1)} km/h | CPI ${metric?.cpi.toFixed(2)}`).addTo(group); }); cameras.forEach(([name, id, lat, lng]) => L.circleMarker([lat, lng], { radius: 6, color: "#1e3a8a", weight: 2, fillColor: "#fff", fillOpacity: 1 }).bindTooltip(`<b>${name}</b><br/><span>${id}</span>`).addTo(group)); if (trajectory) { L.polyline(trajectory.route, { color: "#173b85", weight: 8, opacity: .86 }).addTo(group); const line = L.polyline(trajectory.route, { color: "#2563eb", weight: 4, opacity: 1 }).addTo(group); current.fitBounds(line.getBounds(), { padding: [42, 42] }); trajectory.waypoints.forEach(point => L.marker([point.latitude, point.longitude], { icon: L.divIcon({ className: "waypoint", html: `<b>${point.sequence}</b>`, iconSize: [25, 25], iconAnchor: [12, 12] }) }).bindPopup(`<b>${point.junction}</b><br/>${point.arrival_ist}<br/><b>${point.transit_speed_kph} km/h</b>`).addTo(group)); } }, [corridors, trajectory]);
  return <div className="map-wrap"><div className="map-label">GMDA / DELHI POLICE · LIVE OPERATIONAL MAP <span>WGS84 · EPSG:4326</span></div><div ref={container} className="map" /></div>;
}
